config/routes.rb
Rails.application.routes.draw do
  get 'monstruos/index', to: 'monstruos#index'

  resources :tweets
  resources :monstruos do
    collection do
      get 'ver'
      get 'show/:id', to: 'monstruos#show', as: 'show' #ta por defecto
    end
  end

  
  root 'tweets#default'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/monstruo.rb
class Monstruo < ActiveRecord::Base
  has_many :tweets
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :monstruo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/monstruos_controller.rb
class MonstruosController < ApplicationController
  def index

  end

  def show
    @monstruo=Monstruo.find(params[:id])

  end
  
  def ver



  end
  
  def destroy
    monstruo = Monstruo.find(params[:id])
    monstruo.destroy
    redirect_to monstruos_path
  end
end

app/controllers/tweets_controller.rb
# encoding = utf-8
class TweetsController < ApplicationController
  
  def default
    
  end
  
  def index
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/monstruos_helper.rb
module MonstruosHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/_header.html.erb
<header>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          
          
          <%= link_to root_path, class: 'navbar-brand' do %>
            <%= image_tag "logo.png", title: "Logo", class: "logo" %>
            Critter
          <% end %>
        </div>
        <div class="collapse navbar-collapse">
          
        </div><!--/.nav-collapse -->
      </div>

    </div>
  </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lab3</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>




</head>
<body>

<%= render 'layouts/header' %>
<%= javascript_pack_tag 'application' %>
<div class="container"> 
<%= yield %>
</div>

</body>
</html>

app/views/monstruos/index.html.erb
<!------------------------------------------------------ 
Acá va a ir el listado de monstruos usando los tags  
<ul> y <li>.
Debe tener un título y mostrar el nombre (en negrita) y
la descripción.
------------------------------------------------------>

HACER <br>
/app/views/monstruos/index.html.erb <br> <br>



<% Monstruo.all.each do |monstruo| %>
<dl>
	<dt>
		<h1> <%=link_to monstruo.nombre , show_monstruos_path(monstruo)%></h1>
	</dt>
	<dd>
		<p>
			<%=monstruo.descripcion%>
		</p>

	<%if monstruo.tweets.count > 1 %>
		<p id="destacado">Twittero destacado! </p>
	<%end%>
		
		<%=link_to "Eliminar monstruo",
		monstruo,
		method: :delete,
		data: {confirm: "Seguro pa?"},
		class: 'btn btn-danger'
		%>
		
	</dd>
</dl>
<% end %>

app/views/monstruos/show.html.erb
Ver un monstruo <br>
/app/views/monstruos/show.html.erb

<h1><%= @monstruo.nombre %></h1>

<h4><%= @monstruo.descripcion %></h4>

<p>Twits del usuario </p>
<%id=@monstruo.id %>
<% tweets=Tweet.where(monstruo_id:id) %>
<ul>
	<%tweets.each do |tw| %>
		<li><%= tw.estado %></li>
	<% end %>
</ul>
<%if tweets.count == 0 %>
	<p>No se han encontrado twits. Que mal!</p>
<%end%>


<!-- <%monstruo=Monstruo.find(params[:id]) %>  Esto está MAL (se hace desde la vista)

<%= monstruo.nombre %>  super recomendable -->


<div>

	<h1> <%=image_tag("logo.png") %> </h1>
	
	<%=link_to "Volver", monstruos_path%>

</div>

app/views/monstruos/ver.html.erb
<!------------------------------------------------------ 
Debe mostrarse la información del primer monstruo sin
usar el id.
Se debe mostrar el nombre (como título) y la descripción 
(como párrafo).
------------------------------------------------------>

HACER <br>
/app/views/monstruos/ver.html.erb

<%=  monstruo=Monstruo.first%>
<h1> <%= monstruo.nombre%>: </h1>
<ul>
	<p>Descripción: <%= monstruo.descripcion%> </p>
</ul>

app/views/tweets/default.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-8">
      <h1> Bienvenido a Critter </h1>
      <h3> Esperamos que encuentre su visita agradable</h3>      
  </div>
  <div class="clearfix visible-xs-block"></div>
  <div class="col-xs-6 col-sm-4">
      <h2>¿Qué desea hacer?</h2>
      <ul>
        <li> <%= link_to "Listado de Monstruos", monstruos_path %></li>
        <li> <%= link_to "Ver el primer monstruo", ver_monstruos_path %></li>
      </ul> 
  </div>
</div>
<div class="row">
  <div class="col-md-6 col-md-offset-1">
    <br><br>
    <h4>Correo: pipito@monstruos.twit.com</h4>
    <a href="https://www.facebook.com"><h4>Faisbok</h4></a>
    <a href="https://www.twitter.com"><h4>Twiter (oh the irony)</h4></a>
    
  </div>
</div>

app/views/tweets/index.html.erb
<!-- Listado de tweets -->

<h1> HOLA</h1>

app/views/tweets/show.html.erb
<!-- Ver un tweet -->